# Generated by Django 4.2.1 on 2023-05-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0002_alter_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
    ]
