# Generated by Django 4.2.1 on 2023-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0004_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
