# Generated by Django 4.2.1 on 2023-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0006_alter_content_description_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='titre',
            field=models.CharField(max_length=30),
        ),
    ]
