# Generated by Django 4.2.1 on 2023-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0007_alter_content_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
