# Generated by Django 4.2.1 on 2023-05-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0011_remove_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
