# Generated by Django 4.2.1 on 2023-05-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0012_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('B', 'Blog'), ('P', 'Portfolio')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
